### ISSUE TITLE
Youtube Display Size

### ISSUE THREAD

**Issue by AndyC3108** [eouia/MMM-AssistantMk2#68]
Hi & thank you in advance for you help.

When the Youtube app opens it is full screen.  Is there a way of resizing it so that other MagicMirror modules are still visible?

Kind regards...

Andy

**Comment by eouia** [comment]
You can adjust CSS properties. 
Add this into your `css/custom.css` and modify as your wish.
```css
#ASSISTANT_SCREEN {
  position:fixed:
  width:400px;
  height:300px;
  top: 10px;
  left:10px;
}
```
